### ISSUE TITLE
VT not working correctly on Airplane 95 or newer

### ISSUE THREAD

**Issue by LcorpOfficial** [MC-Machinations/VanillaTweaks#43]
This server is running Airplane version git-Airplane-102 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8daada0 on HEAD)

on my main prod server no errors in console on airplane 102, but on 95 i got this error when trying to run `/vt`

on Airplane 95 (test server, locally hosted) it functions fine.

```
[09:28:22] [Server thread/INFO]: LcorpOfficial issued server command: /vt
[09:28:22] [Netty Epoll Server IO #1/ERROR]: Packet encoding of packet ID 15 threw (skippable? true)
java.lang.NoClassDefFoundError: me/machinemaker/vanillatweaks/adventure/translations/MappedTranslatableComponent
	at me.machinemaker.vanillatweaks.adventure.translations.MappedTranslatableComponentRenderer.render(MappedTranslatableComponentRenderer.java:62) ~[VanillaTweaks-Paper.jar:?]
	at me.machinemaker.vanillatweaks.adventure.translations.MappedTranslatableComponentRenderer.render(MappedTranslatableComponentRenderer.java:39) ~[VanillaTweaks-Paper.jar:?]
	at net.kyori.adventure.translation.GlobalTranslator.render(GlobalTranslator.java:73) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.papermc.paper.adventure.PaperAdventure.asJsonString(PaperAdventure.java:180) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.network.FriendlyByteBuf.writeComponent(FriendlyByteBuf.java:358) ~[app:?]
	at net.minecraft.network.protocol.game.ClientboundChatPacket.write(ClientboundChatPacket.java:34) ~[app:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[patched_1.17.1.jar:git-Airplane-95]
	at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.0.1.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.0.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268) ~[ProtocolLib.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.17.1.jar:git-Airplane-95]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274) ~[ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Airplane-95]
	at com.ticxo.modelengine.nms.v1_17_1_R1.packet.MEChannelHandler.write(MEChannelHandler.java:79) ~[Model-Engine-r2.1.8.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Airplane-95]
	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:108) ~[TAB.v2.9.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.1.jar:git-Airplane-95]
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.a(Connection.java:450) ~[app:?]
	at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:424) ~[app:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Airplane-95]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by Machine-Maker** [comment]
I can't replicate this. Am on `This server is running Airplane version git-Airplane-102 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8daada0 on HEAD)` with the [latest release of this plugin](https://github.com/MC-Machinations/VanillaTweaks/releases/tag/v0.2.0-beta.10), and the vt command doesn't produce that error stacktrace, just the usage message. Can you list your plugins? Maybe something else is conflicting.

**Comment by LcorpOfficial** [comment]
Sure.

 Prod Server:
``` Plugins (64): AdvancedHelp, AngelChest, ArmorStandTools, AuctionHouse, AutomatedCrafting, BetonQuest, BuycraftX, CMILib, Citizens, ClearLag, ColoredAnvils, CommandHook, CoreProtect, CustomCrafting, DeathMessagesPrime, DiscordSRV, DiscordSRV-Staff-Chat, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, F3Name, FastAsyncWorldEdit, FeatherBoard, GSit, GriefPrevention, HeadDatabase, HiveChecker, HolographicDisplays, ImageOnMap, InteractionVisualizer, InteractiveBooks, InteractiveChat, InteractiveChatDiscordSrvAddon, LibsDisguises, LightAPI, LuckPerms, MobsToEggs, ModelEngine, Multiverse-Core, MythicCrucible, MythicMobs, NexelWilderness, OpenAudioMc, PerWorldInventory, PlaceholderAPI, PlayerWarps, ProtocolLib, PvPManager, QuickShop, RealEstate, SerialKey, ServerUtils, ShulkerPacks, TAB, TradeMe, Vault, ViaVersion, Vivecraft-Spigot-Extensions, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, mcMMO and spark```

Test Server
```Plugins (62): AdvancedHelp, AngelChest, ArmorStandTools, AuctionHouse, AutomatedCrafting, BetonQuest, BuycraftX, CMILib, Citizens, ClearLag, ColoredAnvils, CommandHook, CoreProtect, CustomCrafting, DeathMessagesPrime, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, F3Name, FastAsyncWorldEdit, FeatherBoard, GSit, GriefPrevention, HeadDatabase, HiveChecker, HolographicDisplays, ImageOnMap, InteractionVisualizer, InteractiveBooks, InteractiveChat, LibsDisguises, LightAPI, LuckPerms, MobsToEggs, ModelEngine, Multiverse-Core, MythicCrucible, MythicMobs, NexelWilderness, OpenAudioMc, PerWorldInventory, PlaceholderAPI, PlayerWarps, ProtocolLib, PvPManager, QuickShop, RealEstate, SerialKey, ServerUtils, ShulkerPacks, TAB, TradeMe, VanillaTweaks, Vault, ViaVersion, Vivecraft-Spigot-Extensions, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, mcMMO and spark```

**Comment by Machine-Maker** [comment]
Ok, that's rather a lot. Would you mind just copying your airplane jar that's giving you issues and *just* this plugin to a new directory and run the server to confirm that it works with only VanillaTweaks?

**Comment by LcorpOfficial** [comment]
haha it's a long-running server. I can perhaps set up another test environment; but i'm not currently well suited to debug this to the extent of a binary search right now. I'll need some time.

**Comment by Machine-Maker** [comment]
You're saying you dont get the issue with airplane 102 tho right? Can you just use that instead of 95 for the time being?

**Comment by LcorpOfficial** [comment]
same issue on 102, but nothing in console.

**Comment by Machine-Maker** [comment]
Yeah, I just cannot replicate it on 95 or 102 running the command as a player or console. So its just gotta some conflict with another plugin. I even added ViaVersion and ProtocolLib which, in my thinking, are the most likely to cause this as I see them in the error stacktrace, but everything still worked. I am currently working on re-writing the translation system (which will fix this issue cause I will be doing things a different way), but no time table on that.

**Comment by LcorpOfficial** [comment]
no worries for now! it's a low-priority requested function by players as of right now, Would you like to keep this open to keep tabs on this? as the plugin receives other updates I can try them as well.

**Comment by Machine-Maker** [comment]
@LcorpOfficial go ahead and try [this version](https://github.com/MC-Machinations/VanillaTweaks/releases/tag/v0.2.0-beta.11).
