### ISSUE TITLE
Could not create injector. Fails to enable

### ISSUE THREAD

**Issue by DeanMSalter** [MC-Machinations/VanillaTweaks#61]
Using 1.18.1 purpur

11:09:27 ERROR]: Error occurred while enabling VanillaTweaks v0.2.0-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Could not create injector!
        at me.machinemaker.vanillatweaks.VanillaTweaks.onEnable(VanillaTweaks.java:154) ~[PaperTweaks.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1555]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at TreasureGems.<init>(TreasureGems.java:60)
  at PaperTweaks.jar//ModuleRegistry.lambda$configure$1(ModuleRegistry.java:68)
  while locating TreasureGems
  at PaperTweaks.jar//ModuleRegistry.lambda$configure$0(ModuleRegistry.java:67)
  while locating ModuleBase annotated with @Element(setName=,uniqueId=28, type=MAPBINDER, keyType=String)
  at ModuleManager.<init>(ModuleManager.java:85)
      \_ for 2nd parameter moduleMap
  at PaperTweaks.jar//ModuleRegistry.configure(ModuleRegistry.java:70)
  at VanillaTweaks.moduleManager(VanillaTweaks.java:69)
      \_ for field moduleManager
  at PaperTweaks.jar//VanillaTweaks$1.configure(VanillaTweaks.java:139)
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error

**Comment by Machine-Maker** [comment]
Update to 1.18.2. Only the latest minor version is supported.
