### ISSUE TITLE
Errors in the console caused by wandering trades module.

### ISSUE THREAD

**Issue by ExtremorGP** [MC-Machinations/VanillaTweaks#67]
### Expected behavior

Working without errors in the console.

### Observed/Actual behavior

Errors in the console.
`[00:30:23] [Server thread/ERROR]: [VanillaTweaks: WanderingTrades] Could not load wandering trades from data/wandering_trades.json. This module will not work properly
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.bukkit.Material` from String "minecraft:mangrove_planks": not one of the values accepted for Material enum class
 at [Source: (sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream); line: 1628, column: 22] (through reference chain: java.util.ArrayList[203]->me.machinemaker.vanillatweaks.modules.hermitcraft.wanderingtrades.Trade["secondaryCost"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1851) ~[?:?]
	at me.machinemaker.vanillatweaks.config.Mixins$MaterialMixIn$Deserializer.deserialize(Mixins.java:82) ~[PaperTweaks.jar:?]
	at me.machinemaker.vanillatweaks.config.Mixins$MaterialMixIn$Deserializer.deserialize(Mixins.java:76) ~[PaperTweaks.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593) ~[?:?]
	at me.machinemaker.vanillatweaks.modules.hermitcraft.wanderingtrades.WanderingTrades.<init>(WanderingTrades.java:62) ~[PaperTweaks.jar:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:120) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[?:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[?:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[?:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60) ~[?:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[?:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[?:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[?:?]
	at com.google.inject.internal.RealMapBinder$RealMapProvider.doProvision(RealMapBinder.java:794) ~[?:?]
	at com.google.inject.internal.RealMapBinder$RealMapProvider.doProvision(RealMapBinder.java:731) ~[?:?]
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[?:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[?:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[?:?]
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50) ~[?:?]
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[?:?]
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101) ~[?:?]
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245) ~[?:?]
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:140) ~[?:?]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[?:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:69) ~[?:?]
	at com.google.inject.Guice.createInjector(Guice.java:59) ~[?:?]
	at me.machinemaker.vanillatweaks.VanillaTweaks.onEnable(VanillaTweaks.java:135) ~[PaperTweaks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] allay.json could not be turned into an EntityType
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] frog.json could not be turned into an EntityType
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] frog.json could not be turned into an EntityType
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] frog.json could not be turned into an EntityType
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] tadpole.json could not be turned into an EntityType
[00:30:23] [Server thread/WARN]: [VanillaTweaks: MoreMobHeads] warden.json could not be turned into an EntityType`

### Steps/models to reproduce

Run the newest release (v0.2.0-beta.22) on Paper 1.18.2.

### Plugin and Datapack List

Only VanillaTweaks/PaperTweaks.

### Server Version Info

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version

### Plugin Version

Version: 0.2.0-SNAPSHOT

### Other

[latest.log](https://github.com/MC-Machinations/VanillaTweaks/files/9075349/latest.log)

**Comment by Machine-Maker** [comment]
Update to 1.19, or downgrade this plugin to before I updated it to 1.19
