### ISSUE TITLE
PaperTweaks not working (at all)

### ISSUE THREAD

**Issue by 1nfameArts** [MC-Machinations/VanillaTweaks#82]
### Expected behavior

Expected no errors/warns. No "Disabling PaperTweaks...".

### Observed/Actual behavior

[17:00:22 INFO]: An exception was caught and reported. Message: me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.bukkit.World` from String "sillyworldv6": not a valid, loaded world
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[0])
java.lang.IllegalArgumentException: Could not set value of included-worlds to ["sillyworldv6"] from plugins\PaperTweaks\modules\multiplayersleep\config.yml
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.lambda$load$0(SectionNode.java:337) ~[PaperTweaks.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.load(SectionNode.java:324) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.ConfigurationNode.reload(ConfigurationNode.java:69) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.reload(BaseConfig.java:67) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.Reloadable.reloadAndSave(Reloadable.java:75) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.handleFile(BaseConfig.java:129) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:124) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:114) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.MenuModuleConfig.init(MenuModuleConfig.java:99) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.create(BaseConfig.java:269) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.bindConfig(ConfigModule.java:57) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.lambda$configure$0(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.configure(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ModuleBase.configure(ModuleBase.java:55) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.survival.multiplayersleep.MultiplayerSleep.configure(MultiplayerSleep.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.AbstractModule.configure(AbstractModule.java:66) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements.getElements(Elements.java:108) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:238) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:243) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ModuleManager.loadModules(ModuleManager.java:84) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.PaperTweaks.onEnable(PaperTweaks.java:138) ~[PaperTweaks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.bukkit.World` from String "sillyworldv6": not a valid, loaded world
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[0])
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.config.Mixins$WorldMixIn$Deserializer.deserialize(Mixins.java:125) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.config.Mixins$WorldMixIn$Deserializer.deserialize(Mixins.java:114) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4539) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4495) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.lambda$load$0(SectionNode.java:335) ~[PaperTweaks.jar:?]
	... 37 more
[17:00:22 ERROR]: Error occurred while enabling PaperTweaks v0.4.1 (Is it up to date?)
me.machinemaker.papertweaks.libs.com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Could not set value of included-worlds to ["sillyworldv6"] from plugins\PaperTweaks\modules\multiplayersleep\config.yml
  at [unknown source]

1 error
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:238) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:243) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ModuleManager.loadModules(ModuleManager.java:84) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.PaperTweaks.onEnable(PaperTweaks.java:138) ~[PaperTweaks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Could not set value of included-worlds to ["sillyworldv6"] from plugins\PaperTweaks\modules\multiplayersleep\config.yml
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.lambda$load$0(SectionNode.java:337) ~[PaperTweaks.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.load(SectionNode.java:324) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.ConfigurationNode.reload(ConfigurationNode.java:69) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.reload(BaseConfig.java:67) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.Reloadable.reloadAndSave(Reloadable.java:75) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.handleFile(BaseConfig.java:129) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:124) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:114) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.MenuModuleConfig.init(MenuModuleConfig.java:99) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.create(BaseConfig.java:269) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.bindConfig(ConfigModule.java:57) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.lambda$configure$0(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.configure(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ModuleBase.configure(ModuleBase.java:55) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.survival.multiplayersleep.MultiplayerSleep.configure(MultiplayerSleep.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.AbstractModule.configure(AbstractModule.java:66) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements.getElements(Elements.java:108) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[PaperTweaks.jar:?]
	... 16 more
Caused by: me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.bukkit.World` from String "sillyworldv6": not a valid, loaded world
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[0])
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.config.Mixins$WorldMixIn$Deserializer.deserialize(Mixins.java:125) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.config.Mixins$WorldMixIn$Deserializer.deserialize(Mixins.java:114) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4539) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4495) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.lambda$load$0(SectionNode.java:335) ~[PaperTweaks.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.SectionNode.load(SectionNode.java:324) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.ConfigurationNode.reload(ConfigurationNode.java:69) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.reload(BaseConfig.java:67) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.Reloadable.reloadAndSave(Reloadable.java:75) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.handleFile(BaseConfig.java:129) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:124) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.init(BaseConfig.java:114) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.MenuModuleConfig.init(MenuModuleConfig.java:99) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.me.machinemaker.lectern.BaseConfig.create(BaseConfig.java:269) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.bindConfig(ConfigModule.java:57) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.lambda$configure$0(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.machinemaker.papertweaks.modules.ConfigModule.configure(ConfigModule.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.ModuleBase.configure(ModuleBase.java:55) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.modules.survival.multiplayersleep.MultiplayerSleep.configure(MultiplayerSleep.java:47) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.AbstractModule.configure(AbstractModule.java:66) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.spi.Elements.getElements(Elements.java:108) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[PaperTweaks.jar:?]
	at me.machinemaker.papertweaks.libs.com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[PaperTweaks.jar:?]
	... 16 more
[17:00:22 INFO]: Disabling PaperTweaks v0.4.1

### Steps/models to reproduce

I don't know. This just happened. I already upgraded the plugin. But I think this happened after:
1. Stop the server.
2. Change level-name in server.properties
3. Start the server again
4. Bug!

### Plugin and Datapack List

    ViaVersion (v4.9.2)
    LuckPerms (v5.4.108)
    InvSeePlusPlus (v0.24.7)
    ViaBackwards (v4.9.1)
    WorldEdit (v7.3.0-beta-02+e11f161)
    RegisterPlus (v1.4)
    PaperTweaks (v0.4.1)
    Maintenance (v4.2.0)
    InvSeePlusPlus_Give (v0.24.7)
    InvSeePlusPlus_Clear (v0.24.7)
    GSit (v1.6.0)
    elyby-skinsystem (v0.2.0-beta)
    CoreProtect (v22.2)
    spark (v1.10.58)
Datapacks:
None..? I didn't migrate them yet.

### Server Version Info

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

### Plugin Version

v0.4.1

### Other

[Profiler data](https://spark.lucko.me/uwNdHPx0sj) from spark

**Comment by 1nfameArts** [comment]
My opinion on this is that the deserialation algorithm in Paper is causing the errors, just by looking at them and saying some gibberish about it

**Comment by Machine-Maker** [comment]
Does `sillyworldv6` this world exist? You have a reference to that world in some module configuration files and it can't find that world when it loads up.

**Comment by 1nfameArts** [comment]
it does, but not loaded

**Comment by Machine-Maker** [comment]
What do you mean not loaded? Like it is loaded after the plugin or is never loaded? If its never loaded, that is the same as it not existing as far as the server is concerned. If its the latter, and it doesn't exist, you have to remove references to it in the configuration files for this plugin.

If it is the former and is loaded after this plugin, what world management system are you using? It should be setup to have this plugin load after multiverse for example.

**Comment by 1nfameArts** [comment]
i meant that the server literally doesn't load it, because it was told 2 by
level-name
multiverse plugin is not there, so this is probably because of paperTweaks
staying unsynced with the level-name variable
potential fix:
1. find the part responsible for world name finder
2. make it synchronize with the variable

**Comment by Machine-Maker** [comment]
if you changed your level name, you have to change it in the configs too. Having the config automatically change based on the level name is bad design. It should only change when you tell it to change. You have to go and change the world name in the configs if you changed the level name.
